version: '3.3'

services:  

  ingress:
    build:
      context: .
      dockerfile: Dockerfile-ingress
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml
    ports:
      - "8000:80"
      - "8001:8001"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2    

  webapi:
    build:
      context: ../webapp/
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVICE_NAME=webapi
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  webapi_envoy:
    image: envoyproxy/envoy-alpine-dev:latest
    volumes:
    - ./webapi-envoy.yaml:/etc/service-envoy.yaml
    command: ["envoy","-c", "/etc/service-envoy.yaml", "--service-cluster", "proxy-webapi"]
    network_mode: "service:webapi"               

  webfront:
    depends_on:
      - webapi
    image: daljeethcl/webfront:1.0
    restart: always
    environment:
      BACKEND_URL: http://webapi:5000
    environment:
      - SERVICE_NAME=webfront 
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  webfront_envoy:
    image: envoyproxy/envoy-alpine-dev:latest
    volumes:
    - ./webfront-envoy.yaml:/etc/service-envoy.yaml
    command: ["envoy","-c", "/etc/service-envoy.yaml", "--service-cluster", "proxy-webfront"]
    network_mode: "service:webfront"         

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
       