version: '3.3'

services:  

  ingress:
    build:
      context: .
      dockerfile: Dockerfile-ingress
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml
    ports:
      - "8000:80"
      - "8001:8001"
        

  webapi:
    build:
      context: ../webapp/
      dockerfile: Dockerfile
    restart: always

                       
  webapi_envoy:                            
    image: envoyproxy/envoy-alpine-dev:latest 
    volumes:
    - ./webapi-envoy.yaml:/etc/service-envoy.yaml
    command: ["envoy","-c", "/etc/service-envoy.yaml", "--service-cluster", "proxy-webapi"]
    network_mode: "service:webapi"               


    

  webfront:
    depends_on:
      - webapi
    image: daljeethcl/webfront:1.0
    restart: always
    volumes:
    - ../webfront/app.py:/app/app.py
    environment:
      - BACKEND_URL=google.com 


  webfront_envoy:
    image: envoyproxy/envoy-alpine-dev:latest
    volumes:
    - ./webfront-envoy.yaml:/etc/service-envoy.yaml
    command: ["envoy","-c", "/etc/service-envoy.yaml", "--service-cluster", "proxy-webfront"]
    network_mode: "service:webfront"         

       
