apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: webapp
        image: daljeethcl/web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
