apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfront-deployment
  labels:
    app: webfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfront
  template:
    metadata:
      labels:
        app: webfront
    spec:
      containers:
      - name: webfront
        image: daljeethcl/webfront:1.0
        env:
        - name: BACKEND_URL
          value: "http://webservice"            
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

 
